### ISSUE TITLE
First launch will always result in a crash, subsequent launches work fine

### ISSUE THREAD

**Issue by SplendidAlakey** [kb-1000/JumpQuilt#3]
**MC** 1.19.2
**JumpQuilt** 2.3.0

1. Make a new instance with Forge 43.2.0 (or any version, really)
2. Add JumpQuilt
3. Launch the game and crash
4. Launch the game again - now everything works

Logs: https://gist.github.com/SplendidAlakey/b80dc6af74c4bed007529a9165707338

**Comment by kb-1000** [comment]
Can't reproduce.
Works on first launch over here.

**Comment by SplendidAlakey** [comment]
Could it be something system related? I can reproduce it 100% consistently on Prism Launcher and CF app. Running Nvidia GTX980 and 16GB RAM at 2133mhz, Windows 10.

**Comment by kb-1000** [comment]
I don't have any Nvidia GPU or Windows system able to run MC to verify that, but that doesn't sound like JumpQuilt's fault.

**Comment by SplendidAlakey** [comment]
Hmm.. alright. I suspect it's something to do with how Windows manages processes. The error used to be a bit different on previous versions of Forge, it said something along the lines of "[...] can't initialize [...], because library is already in use [...]". So I chalked it up to JumpQuilt being technically ran on Forge first, and so some necessary library was being used by Forge already, which made Quilt crash. I only reported it now, because the error message changed to what it is now, so I thought maybe it's something else.

If you believe it's not a JQ issue, feel free to close this. Otherwise, I'll keep it open for visibility. I've seen at least 1 other person over at Quilt's Discord having the same issue a while ago.

**Comment by kb-1000** [comment]
Thinking a bit more about it, I'd blame the download progress window, which uses LWJGL already, which might cause it to refuse to initialize a second time.
Can you reproduce this using Jumploader as well?

**Comment by SplendidAlakey** [comment]
I tried supplying a config, that disables that window, before the initial launch. Didn't help.

Jumploader doesn't work for me at all:

```
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.lang.Object java.nio.file.spi.FileSystemProvider.lock accessible: module java.base does not "opens java.nio.file.spi" to module jumploader
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at LAYER SERVICE/jumploader@2.1.3/link.infra.jumploader.launch.ReflectionUtil.reflectStaticField(ReflectionUtil.java:17)
	at LAYER SERVICE/jumploader@2.1.3/link.infra.jumploader.launch.serviceloading.FileSystemProviderAppender.handlePreLaunch(FileSystemProviderAppender.java:37)
	at LAYER SERVICE/jumploader@2.1.3/link.infra.jumploader.launch.PreLaunchDispatcher.dispatch(PreLaunchDispatcher.java:21)
	at LAYER SERVICE/jumploader@2.1.3/link.infra.jumploader.Jumploader.onLoad(Jumploader.java:132)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:116)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:116)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:48)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Exiting with ERROR
Process exited with code 2.
```

**Comment by kb-1000** [comment]
As I'm still unable to reproduce this, I'll have to ask you to help debugging this.
Could you please attach a debugger and set a breakpoint on ExceptionInInitializerError?

**Comment by SplendidAlakey** [comment]
Nothing shows up, when I'm looking specifically for ExceptionInInitializerError. If I look for any exception, I get a ton, although not sure how relevant, since all of them are caught and handled.

**Comment by FibreTTP** [comment]
Happens to me too on both Quilt beta and release channels, and on Adoptium and Amazon Corretto JDKs.

My logs are practically the same:
[Quilt Loader crash log on first launch](https://gist.github.com/FibreTTP/24c80266c1fdd04103a9c530f4da7744).
[Minecraft log on first launch crash](https://gist.github.com/FibreTTP/1ba982f51a6a37f10bb3607ec3cee80d).
[Subsequent Minecraft log after first launch crash](https://gist.github.com/FibreTTP/0cf944ab147a5d76bdadfe3dbf88429a).

There is a [modpack](https://www.curseforge.com/minecraft/modpacks/quantum-freedom) on CurseForge using JumpQuilt that warns "sometimes the pack crashes on first launch please launch a second time and it will launch successfully."

**Comment by Taxrosdev** [comment]
I am noticing exact same bug.

Logs Attached here [crash-2023-02-12_24.16.09.1328-quilt_loader.txt](https://github.com/kb-1000/JumpQuilt/files/10713481/crash-2023-02-12_24.16.09.1328-quilt_loader.txt)

OS: Linux x64 Arch Linux
[crash-2023-02-12_24.16.09.1328-quilt_loader.txt](https://github.com/kb-1000/JumpQuilt/files/10713481/crash-2023-02-12_24.16.09.1328-quilt_loader.txt)

GPU: Nvidia RTX 3060
Launching with 3rd party launch [PortableMC](https://github.com/mindstorm38/portablemc)

Edit: Fixed Link to PortableMC

**Comment by kb-1000** [comment]
Sounds like an Nvidia driver bug, then.
But as said, without you helping further debugging this as mentioned above, I have no way of debugging or fixing anything here.

**Comment by SplendidAlakey** [comment]
CF now natively supports QL, so closing this.
